version: '3.8'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      - MONGODB_URL=mongodb://mongo:27017/db_muhamadimron_betest
      - JWT_SECRET=lakjsdlfjlkasdfoiasjf
    depends_on:
      - mongo
      - redis
    volumes:
      - .:/app

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:latest
    ports:
      - '6379:6379'

volumes:
  mongo-data: